version: '3.8'
services:
    pgmaster:
        image: postgres:latest
        restart: always
        container_name: pgmaster
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        ports:
            - '8080:5432'
        volumes:
            - pgmaster:/var/lib/postgresql/data
    redis:
        image: redis:latest
        restart: always
        container_name: redis
        command: redis-server --save 20 1 --loglevel warning
        ports:
            - '8081:6379'
        volumes:
            - redis:/data
    # server:
    #     image: express-graphql-app
    #     restart: always
    #     container_name: server
    #     ports:
    #         - '4000:4000'
    #     env_file:
    #         - .env.docker
    #     depends_on:
    #         - pgmaster
    #         - redis
    # client:
    #     image: nextjs-docker
    #     restart: always
    #     container_name: client
    #     ports:
    #         - '3000:3000'
    #     depends_on:
    #         - pgmaster
    #         - redis
            - server

volumes:
    pgmaster:
        driver: local
    redis:
        driver: local
