version: '3.8'
services:
    pgmaster:
        image: postgres:latest
        restart: always
        container_name: pgmaster
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        ports:
            - '8080:5432'
        volumes:
            - pgmaster:/var/lib/postgresql/data
volumes:
    pgmaster:
        driver: local
