version: '3.8'
services:
    pgmaster:
        image: postgres:latest
        restart: always
        container_name: pgmaster
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db
        ports:
            - '8080:5432'
        volumes:
            - pgmaster:/var/lib/postgresql/data
    redismaster:
        image: redis:latest
        restart: always
        container_name: redismaster
        command: redis-server --save 20 1 --loglevel warning
        ports:
            - '8081:6379'
        volumes:
            - redismaster:/data
    # expressmaster:
    #     image: express-graphql-app
    #     restart: always
    #     container_name: expressmaster
    #     ports:
    #         - '4000:4000'
    #     env_file:
    #         - .env
    #     depends_on:
    #         - pgmaster
    #         - redismaster
    # clientmaster:
    #     image: nextjs-docker
    #     restart: always
    #     container_name: clientmaster
    #     ports:
    #         - '3000:3000'
    #     depends_on:
    #         - pgmaster
    #         - redismaster
    #         - expressmaster

volumes:
    pgmaster:
        driver: local
    redismaster:
        driver: local
